package by.htp.les04.controller.command;

public enum CommandName {
	
	LOGINATION, 
	REGISTRATION, 
	SAVENEWUSER, 
	GOTOINDEXPAGE, 
	GOTOMAINPAGE,
	LOGOUT,
	GO_TO_FULL_NEWS_PAGE,
	GO_TO_EDIT_PAGE,
	SAVE_NEW_INFORMATION,
	LOCALIZATION,
	DELETE_NEWS,
	GO_TO_ERROR_PAGE,
}
